-- Drop existing project table and recreate with EfisProjectId as ProjectID
DROP TABLE IF EXISTS project;

CREATE TABLE project (
  ProjectID VARCHAR(20) NOT NULL,
  ProjectName varchar(100) NOT NULL,
  District varchar(10) NOT NULL DEFAULT '',
  DistrictLocation char(2) DEFAULT NULL,
  County varchar(10) DEFAULT NULL,
  Route varchar(10) DEFAULT NULL,
  PMFrom varchar(10) DEFAULT NULL,
  PMTo varchar(10) DEFAULT NULL,
  StartedDate date DEFAULT NULL,
  EstimatedDeliveryDate date DEFAULT NULL,
  RequestedDate date DEFAULT NULL,
  ClientDueDate date DEFAULT NULL,
  ApprovedDate date DEFAULT NULL,
  SampledDate date DEFAULT NULL,
  SampleReceivedDate date DEFAULT NULL,
  ToGradeBenchDate date DEFAULT NULL,
  StaffDueDate date DEFAULT NULL,
  GLTrackNumber varchar(20) NOT NULL DEFAULT '',
  EA varchar(20) NOT NULL DEFAULT '',
  StructureNumber varchar(20) DEFAULT NULL,
  FA tinyint unsigned DEFAULT NULL,
  ActivityCode smallint(3) unsigned zerofill DEFAULT '000',
  MSACode varchar(20) DEFAULT NULL,
  SubJob varchar(40) DEFAULT NULL,
  SpecialDesignation varchar(40) DEFAULT NULL,
  T_101Numbers varchar(200) DEFAULT NULL,
  ClientOffice varchar(50) DEFAULT NULL,
  ClientPhone varchar(20) DEFAULT NULL,
  ClientLastName varchar(30) DEFAULT NULL,
  ClientFirstName varchar(30) DEFAULT NULL,
  CreatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CreatedBy varchar(50) DEFAULT NULL,
  UpdatedBy varchar(50) DEFAULT NULL,
  PRIMARY KEY (ProjectID),
  KEY idx_project_name (ProjectName),
  KEY idx_project_district (District),
  KEY idx_project_route (Route),
  KEY idx_project_started_date (StartedDate),
  KEY idx_project_client_due_date (ClientDueDate),
  KEY idx_project_gl_track_number (GLTrackNumber)
);
